# Site settings
title: Frieder Mitsch
author: 
  name: Frieder Mitsch
  email: f.mitsch@lse.ac.uk
  Institution: [LSE website](https://www.lse.ac.uk/International-Inequalities/People/frieder-mitsch)

# Build settings
remote_theme: jekyll/minima
